### PR TITLE
Replacing the series data with the California data.

### LINKED ISSUE #12: Add CA job series informaiton
CA users creating a task should be able to view and select CA job series

### Acceptance Criteria
-Job series dropdown should have information from https://github.com/chhsdata/openopps-platform/blob/dev/tools/init-tag-data/series.yml 
(Caveat from Jon: he modified the ingest process to accept yml. (https://github.com/chhsdata/openopps-platform/blob/dev/tools/lib/dbTools.js) 
- User viewing a task should see what job series it is for

### Mocks
image

### PR DESCRIPTION
**Pull request by DavidEBest**
Fixes #12 

Adds the series yml file from the old chhsdata repo, adds yml parsing, and removes the federal government series data.

### CODE REVIEW

**Comment by amprokop** [comment]
image

Looks good. Merging

**Comment by amprokop** [comment]
Oops. My testing was bad. The old series data is still appearing in the UI for me, as shown in that screenshot. Does there need to be a migration here?

**Comment by DavidEBest** [comment]
Shoot. I didn't add anything to remove the existing data, I just made it so
when you run it for the first time it populates with the California series
data.

**Comment by amprokop** [comment]
Got it. So a fresh clone will work 😁

**Pull request merged**
